name: Build and Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build-and-release:
    name: Build and Release
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            binary_name: gradient
          - os: windows-latest
            target: x86_64-pc-windows-gnu
            binary_name: gradient.exe
          - os: macos-latest
            target: x86_64-apple-darwin
            binary_name: gradient

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}
          override: true

      - name: Build
        run: cargo build --release --target ${{ matrix.target }}

      - name: Rename binary
        run: |
          mv target/${{ matrix.target }}/release/${{ matrix.binary_name }} target/${{ matrix.target }}/release/gradient-${{ matrix.target }}
        if: matrix.os != 'windows-latest'

      - name: Rename binary (Windows)
        run: |
          move target\${{ matrix.target }}\release\${{ matrix.binary_name }} target\${{ matrix.target }}\release\gradient-${{ matrix.target }}.exe
        if: matrix.os == 'windows-latest'

      - name: Create Release and Upload Artifact
        uses: softprops/action-gh-release@v1
        with:
          files: |
            target/${{ matrix.target }}/release/gradient-${{ matrix.target }}${{ matrix.os == 'windows-latest' && '.exe' || '' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
